server:
  port: 8020
  datasource:
    url: jdbc:mysql://47.103.198.18/test
    name: remote
    password: remotepwd
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
